### ISSUE TITLE
Can not works.

### ISSUE THREAD

**Issue by Nanapiou** [VintellX/Discord-Nitro#4]
Since the file ("Nitro Codes.txt") is full of "https://discordgift/{code}", in the following loop:

```py
for line in file.readlines():
    nitro = line.strip("\n")
```

`nitro` is in the same format (https://...), so 

```py
url = f"https://discordapp.com/api/v9/entitlements/gift-codes/{nitro}?with_application=false&with_subscription_plan=true"
```
creates an url that looks very weird, that will throw a `404` error at any times.

There's another problem: rate limits
Discord is hard limiting this endpoint, so it will blocks like 9/10 codes

**Comment by RXNationGMG** [comment]
seems like there is an issue to the code...

**Comment by AntiGamerPlayzz** [comment]
Can not work.*
